---
defaults:
  install_options: --source http://gems.rubyforge.org --source http://gems.github.com
gems:
- name: rdoc
  version: >= 2.4.3
- name: rake
  version: >= 0.8.7
- name: rspec
  version: 1.2.8
- name: rspec-rails
  version: 1.2.7.1
- name: actionmailer
  version: 2.0.2
- name: actionpack
  version: 2.0.2
- name: activerecord
  version: 2.0.2
- name: activeresource
  version: 2.0.2
- name: activesupport
  version: 2.0.2
- name: mysql
  version: ~> 2.7.0
- name: rails
  version: 2.0.2
- name: vlad
  version: ~> 1.3.2
